// auto generated by github.com/sakura-rip tool
// Version: develop@v1
// DO NOT EDIT

package dao

import (
	"context"
	"fmt"
	"time"

	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"
)

const (
	DB_NAME = "DB_NAME"
)

type GroupDaoClient struct {
	session *mongo.Client
	ctx     context.Context
	Col     *mongo.Collection
}

func NewGroupDaoClient() *GroupDaoClient {
	cl := &GroupDaoClient{
		session: connectToMongoDB(),
		ctx:     context.Background(),
	}
	cl.Col = cl.session.Database(DB_NAME).Collection("Group")
	return cl
}

type UserDaoClient struct {
	session *mongo.Client
	ctx     context.Context
	Col     *mongo.Collection
}

func NewUserDaoClient() *UserDaoClient {
	cl := &UserDaoClient{
		session: connectToMongoDB(),
		ctx:     context.Background(),
	}
	cl.Col = cl.session.Database(DB_NAME).Collection("User")
	return cl
}

// connectToMongoDB connect to mongo
func connectToMongoDB() *mongo.Client {
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	db, err := mongo.Connect(ctx, options.Client().ApplyURI("mongodb://localhost:27017"))
	if err != nil {
		panic(fmt.Errorf("error on init mongo db: %v", err))
	}
	return db
}
