// auto generated by github.com/sakura-rip tool
// Version : develop@v1
// DO NOT EDIT

package dao

import (
	"github.com/sakura-rip/mongodbgen/sample"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/mongo/options"
)

func (cl *GroupDaoClient) DeleteOne(id string) (int64, error) {
	result, err := cl.Col.DeleteOne(cl.ctx, bson.M{"_id": id})
	if err != nil {
		return 0, err
	}
	return result.DeletedCount, err
}

func (cl *GroupDaoClient) DeleteMany(attr bson.M) (int64, error) {
	result, err := cl.Col.DeleteMany(cl.ctx, attr)
	if err != nil {
		return 0, err
	}
	return result.DeletedCount, err
}

func (cl *GroupDaoClient) InsertOne(group *sample.Group) (string, error) {
	result, err := cl.Col.InsertOne(cl.ctx, group)
	if err != nil {
		return "", err
	}
	if oid, ok := result.InsertedID.(string); ok {
		return oid, nil
	}
	return "", nil
}

func (cl *GroupDaoClient) InsertMany(objs []interface{}) ([]string, error) {
	result, err := cl.Col.InsertMany(cl.ctx, objs)
	if err != nil {
		return nil, err
	}
	var strIds []string
	for _, id := range result.InsertedIDs {
		strIds = append(strIds, id.(string))
		return strIds, nil
	}
	return strIds, nil
}

func (cl *GroupDaoClient) UpdateAttribute(id string, attrToUpdate bson.M) error {
	_, err := cl.Col.UpdateOne(cl.ctx, bson.M{"_id": id}, Set(attrToUpdate))
	return err
}

func (cl *GroupDaoClient) DeleteAttributes(id string, attrToDelete bson.M) error {
	_, err := cl.Col.UpdateOne(cl.ctx, bson.M{"_id": id}, Unset(attrToDelete))
	return err
}

func (cl *GroupDaoClient) AddToArray(id string, object bson.M) error {
	_, err := cl.Col.UpdateOne(cl.ctx, bson.M{"_id": id}, AddToSet(object))
	return err
}

func (cl *GroupDaoClient) RemoveFromArray(id string, object bson.M) error {
	_, err := cl.Col.UpdateOne(cl.ctx, bson.M{"_id": id}, Pull(object))
	return err
}

func (cl *GroupDaoClient) Get(filter bson.M) ([]sample.Group, error) {
	res, err := cl.Col.Find(
		cl.ctx, filter)
	if err != nil {
		return nil, err
	}
	var groups []sample.Group
	if err := res.Decode(&groups); err != nil {
		return nil, err
	}
	return groups, err
}

func (cl *GroupDaoClient) GetGroup(id string) (sample.Group, error) {
	res := cl.Col.FindOne(
		cl.ctx,
		bson.D{{"_id", id}},
	)
	var group sample.Group
	if err := res.Decode(&group); err != nil {
		return group, err
	}
	return group, nil
}

func (cl *GroupDaoClient) GetAll() ([]sample.Group, error) {
	res, _ := cl.Col.Find(cl.ctx, bson.M{})
	var groups []sample.Group
	if err := res.All(cl.ctx, &groups); err != nil {
		return groups, err
	}
	return groups, nil
}

func (cl *GroupDaoClient) GetAttribute(id string, attributes bson.D) (sample.Group, error) {
	res := cl.Col.FindOne(
		cl.ctx,
		bson.D{{"_id", id}},
		options.FindOne().SetProjection(attributes),
	)
	var group sample.Group
	if err := res.Decode(&group); err != nil {
		return group, err
	}
	return group, nil
}

func (cl *GroupDaoClient) GetAttributes(id string, attributes ...string) (sample.Group, error) {
	var projections = bson.D{}
	for _, attribute := range attributes {
		projections = append(projections, bson.E{Key: attribute, Value: 1})
	}
	return cl.GetAttribute(id, projections)
}
