// auto generated by https://github.com/sakura-rip/mongodb-gen
// Version : develop@v1
// DO NOT EDIT

package dao

import (
	"github.com/sakura-rip/mongodb-gen/sample"
	"go.mongodb.org/mongo-driver/bson"
)

func (cl *GroupDaoClient) InsertOrUpdateGroupName(id string, newName string) error {
	return cl.UpdateAttribute(id, bson.M{"name": newName})
}

func (cl *GroupDaoClient) DeleteGroupName(id string) error {
	return cl.DeleteAttributes(id, bson.M{"name": 1})
}

func (cl *GroupDaoClient) GetGroupName(id string) (val string, err error) {
	group, err := cl.GetAttributes(id, "name")
	if err != nil {
		return val, err
	}
	return group.Name, err
}

func (cl *GroupDaoClient) GetGroupByName(name string) ([]sample.Group, error) {
	groups, err := cl.Get(bson.M{"name": name})
	if err != nil {
		return nil, err
	}
	return groups, nil
}
