// auto generated by github.com/sakura-rip tool
// Version : develop@v1
// DO NOT EDIT

package dao

import (
	"github.com/sakura-rip/mongodbgen/sample"
	"go.mongodb.org/mongo-driver/bson"
)

func (cl *UserDaoClient) InsertOrUpdateUserHoge(id string, newHoge interface{}) error {
	return cl.UpdateAttribute(id, bson.M{"hoge": newHoge})
}

func (cl *UserDaoClient) DeleteUserHoge(id string) error {
	return cl.DeleteAttributes(id, bson.M{"hoge": 1})
}

func (cl *UserDaoClient) GetUserHoge(id string) (val interface{}, err error) {
	user, err := cl.GetAttributes(id, "hoge")
	if err != nil {
		return val, err
	}
	return user.Hoge, err
}

func (cl *UserDaoClient) GetUserByHoge(hoge interface{}) ([]sample.User, error) {
	users, err := cl.Get(bson.M{"hoge": hoge})
	if err != nil {
		return nil, err
	}
	return users, nil
}
