// auto generated by https://github.com/sakura-rip/mongodb-gen
// Version : develop@v1
// DO NOT EDIT

package dao

import (
	"github.com/sakura-rip/mongodb-gen/sample"
	"go.mongodb.org/mongo-driver/bson"
)

func (cl *UserDaoClient) InsertOrUpdateUserFuck(id string, newFuck int) error {
	return cl.UpdateAttribute(id, bson.M{"fuck": newFuck})
}

func (cl *UserDaoClient) DeleteUserFuck(id string) error {
	return cl.DeleteAttributes(id, bson.M{"fuck": 1})
}

func (cl *UserDaoClient) GetUserFuck(id string) (val int, err error) {
	user, err := cl.GetAttributes(id, "fuck")
	if err != nil {
		return val, err
	}
	return user.Fuck, err
}

func (cl *UserDaoClient) GetUserByFuck(fuck int) ([]sample.User, error) {
	users, err := cl.Get(bson.M{"fuck": fuck})
	if err != nil {
		return nil, err
	}
	return users, nil
}
